### ISSUE TITLE
## Checklist run

### ISSUE THREAD

**Issue by HUMM1984** [semver/semver#776]
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``
* [x] The link is freely available for everyone to read without the need to pay or to create a free account
* [x] I placed the link at the bottom of its category.
* [x] I acknowledge that there's another curation step and that merging this pull request doesn't automatically guarantee the submitted article will be in the newsletter. See [the contributing guides](https://github.com/iOS-Goodies/iOS-Goodies/blob/master/CONTRIBUTING.md#contributing)

## Optional

* [x] Tool is not more than 2 weeks old
* [x] Tool wasn't submitted before 

__Originally posted by @polac24 in https://github.com/iOS-Goodies/iOS-Goodies/pull/2512__

**Comment by jwdonahue** [comment]
Either this was posted to the wrong site or it's click bait.
