### ISSUE TITLE
# Release Checklist

### ISSUE THREAD

**Issue by HUMM1984** [semver/semver#781]
# Release Checklist
- [x] Updated CHANGELOG with latest changes
- [x] Updated latest release and release date in `CHANGELOG.md`
- [x] Tests/CI passes on this Pull Request
- [x] Build Release Candidate finished successfully (`release` workflow)
- [ ] Publish Github Release Page
- [ ] Sanity check docker images (tags 'X.X.X' and 'latest')
- [ ] Sanity check PyPI Packages
- [ ] Sanity check Homebrew core release
- [ ] Update semgrep.dev
- [ ] Update semgrep action
- [ ] Update semgrep-docs

__Originally posted by @mmcqd in https://github.com/returntocorp/semgrep/pull/4403__
